In [2]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(5,)

In [10]:
# Multidimensional
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]
l3 = [3,4,5,6,7]
arr = np.array([l1,l2,l3])

In [11]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [12]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [14]:
#converting into 2 dimensional in single line
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [15]:
arr.shape

(3, 5)